---
abstract: 'Pack data structures so only real content remains'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-Pack
provides:
  Data::Pack:
    file: lib/Data/Pack.pm
    version: 1.100850
requires:
  Carp: 0
  English: 0
  Exporter: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::Differences: 0
  Test::More: 0.88
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Data-Pack
  homepage: http://search.cpan.org/dist/Data-Pack/
  repository: http://github.com/hanekomu/Data-Pack
version: 1.100850
